### PR TITLE
WIP Add esp32c3 module: Lilygo TTGO D1 Plus aka TTGO T-01 Plus.

### PR DESCRIPTION
**Pull request by Burtrum**
Please delete this

### CODE REVIEW

**Comment by acassis** [comment]
Thank you very much @Burtrum ! I think you forgot to run the checkpatch script to catch these coding styles issues:
```
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/include/board.h:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/include/nsh_romfsimg.h:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3-devkit.h:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_adc.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_appinit.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_bmp180.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_board_spi.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_board_spidev.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_board_spislavedev.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_board_wlan.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_boot.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_bringup.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_gc9a01.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_gpio.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_i2c.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_ioctl.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_ledc.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_oneshot.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_reset.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_spiflash.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_st7735.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_st7789.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_uid.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/incubator-nuttx/incubator-nuttx/nuttx/boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/src/esp32c3_wdt.c:2:1: error: Relative file path does not match actual file
Error: Process completed with exit code 1.
```

Normally I do this way:
```
$ ./tools/checkpatch.sh -f boards/risc-v/esp32c3/lilygo-ttgo-t01-plus/include/board.h
```

**Comment by Burtrum** [comment]
Bad pull request. I’ll try again.

**Comment by xiaoxiang781216** [comment]
@Burtrum you don't need close PR, it's more simple to "git push -f your_branch" after your local branch is ready.
